name = "LandauDistribution"
uuid = "6012e1b8-0df6-47e7-96ae-5acef29e6d22"
authors = ["Jerry Ling <proton@jling.dev> and contributors"]
version = "0.2.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1"
Distributions = "0.25"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
